grid_map_filters:

  - name: buffer_normalizer
    type: gridMapFilters/BufferNormalizerFilter

  # # Duplicate layer.
  # - name: duplicate
  #   type: gridMapFilters/DuplicationFilter
  #   params:
  #     input_layer: ...
  #     output_layer: ...

  # Delete color layer.
  - name: delete_original_layers
    type: gridMapFilters/DeletionFilter
    params:
      layers: [color] # List of layers.

  # Fill holes in the map with inpainting.
  - name: inpaint
    type: gridMapCv/InpaintFilter
    params:
      input_layer: elevation
      output_layer: elevation_inpainted
      radius: 1.0 #0.05

  # Reduce noise with a radial blurring filter.
  - name: mean_in_radius
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: elevation_inpainted
      output_layer: elevation_smooth
      radius: 0.06

  # Compute roughness as absolute difference from map to smoothened map.
  - name: roughness
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: roughness
      expression: abs(elevation_inpainted - elevation_smooth)


  # Compute curvature(second derivative of height).
  - name: curvature
    type: gridMapFilters/CurvatureFilter
    params:
      input_layer: elevation_inpainted
      output_layer: curvature

